### ISSUE TITLE
AS A user I WANT to be able to specify which methods a new species is mapped to and whether it is invert sized SO THAT validation doesn't flag these species as being errors

### ISSUE THREAD

**Issue by ccmoloney** [aodn/nrmn-application#539]
Software version: 0.0.344
Environment: systest

From user:
> Invalid method warnings appear for newly added species.  

> How is method characteristics saved when adding new species?  If it isn't then these will come up cumulatively for every new species added

## Notes
1. The system runs a validation check against incoming data to check whether the species is a valid species for the method used to make the observation.  Whether or not a species is valid for a particular method is specified in the database in the methods_species table, which associates observable item IDs with methods.
2. When a new species is entered by a user through the UI (Add Observable Item page) there is currently no way for them to specify the methods that the species is associated with.  As a result, subsequent validation checks for observations of that species will flag it as a WARNING - because it isn't associated with any method in the methods_species table.
3. Ideally the user would have the ability to specify the methods the species is associated with at the time they add the new species.
4. Do they also need to be able to edit the mappings for a species?
5. Also need to be able to specify whether or not the species should use invert sizing.  This is stored as an attribute of the observable_item_ref row in the is_invert_sized column.  This specifies whether the size classes for the species should be interpreted as being fish (false) or invert (true) sizes when non-extended sheets are staged.

## Tasks
- [ ] Update UI to capture the methods associated with the species.  Needs to allow selecting multiple methods
- [ ] Update UI to specify whether or not the species is invert sized
- [ ] Update API to update the methods_species table with the selected mappings
- [ ] DOD

**Comment by bpasquer** [comment]
A cron job has been implemented to refresh the species attribute every night.
https://github.com/aodn/chef-private/pull/3915

**Comment by bpasquer** [comment]
Related to https://github.com/aodn/nrmn-application/issues/550
